<div class="search-global-finder">
    <form action="#" id="form-search-finder">
        <div class="search-global-field _active">
            <input
                    style="position: inherit"
                    type="text"
                    class="search-global-input"
                    id="search-global-finder"
                    name="query">
            <label style="position: inherit" class="search-global-label" for="form-global-finder"></label>
            <button
                    style="position: inherit"
                    type="submit"
                    class="search-global-action"
                    title="<?= $block->escapeHtmlAttr(__('Search')) ?>"
            >
            </button>
        </div>
    </form>
</div>

<style>

</style>